# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoSemanticVersioning < Formula
  desc "Tag your repository with Go!"
  homepage "https://github.com/wpartin/go-semantic-versioning"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/wpartin/go-semantic-versioning/releases/download/v0.5.0/go-semantic-versioning_Darwin_arm64.tar.gz"
      sha256 "dab3e8a49be8234f84ae46ac096533bad7a99d67d76f48b887f9ba28419eefe7"

      def install
        bin.install "go-semantic-versioning"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/wpartin/go-semantic-versioning/releases/download/v0.5.0/go-semantic-versioning_Darwin_x86_64.tar.gz"
      sha256 "66609c68d5afe8b22eb6639110456fa61547ffa6769fd713b643fd9cb82583da"

      def install
        bin.install "go-semantic-versioning"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/wpartin/go-semantic-versioning/releases/download/v0.5.0/go-semantic-versioning_Linux_x86_64.tar.gz"
      sha256 "5e5c409168261ab6d960c181460157ee56dea55340cf7da9e2d9b7d518b18c57"

      def install
        bin.install "go-semantic-versioning"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wpartin/go-semantic-versioning/releases/download/v0.5.0/go-semantic-versioning_Linux_arm64.tar.gz"
      sha256 "4d9c579135ae9409ef3e37531a67cf3129687901d469d45de48ed89b398b5d64"

      def install
        bin.install "go-semantic-versioning"
      end
    end
  end
end
